// <auto-generated />
namespace FilmHaus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update12ReportStatusFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update12ReportStatusFix));
        
        string IMigrationMetadata.Id
        {
            get { return "201712271736184_Update #12 - ReportStatus Fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
