// <auto-generated />
namespace FilmHaus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update10ReviewExpansion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update10ReviewExpansion));
        
        string IMigrationMetadata.Id
        {
            get { return "201712261755468_Update #10 - Review Expansion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
