// <auto-generated />
namespace FilmHaus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update4DropListTag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update4DropListTag));
        
        string IMigrationMetadata.Id
        {
            get { return "201711110057176_Update #4 - Drop ListTag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
