// <auto-generated />
namespace FilmHaus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update8CreatedListTag2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update8CreatedListTag2));
        
        string IMigrationMetadata.Id
        {
            get { return "201711292032385_Update #8 - Created ListTag 2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
