// <auto-generated />
namespace FilmHaus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update13IsActiveforReviews : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update13IsActiveforReviews));
        
        string IMigrationMetadata.Id
        {
            get { return "201801051608239_Update #13 - IsActive for Reviews"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
