//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmHaus.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FilmHaus.Localization.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accolades.
        /// </summary>
        public static string Accolades {
            get {
                return ResourceManager.GetString("Accolades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Members.
        /// </summary>
        public static string ActiveMembers {
            get {
                return ResourceManager.GetString("ActiveMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Reports.
        /// </summary>
        public static string ActiveReports {
            get {
                return ResourceManager.GetString("ActiveReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Reports.
        /// </summary>
        public static string ActivityReports {
            get {
                return ResourceManager.GetString("ActivityReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor(s).
        /// </summary>
        public static string Actors {
            get {
                return ResourceManager.GetString("Actors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Functions.
        /// </summary>
        public static string AdminFunctions {
            get {
                return ResourceManager.GetString("AdminFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search.
        /// </summary>
        public static string AdvancedSearch {
            get {
                return ResourceManager.GetString("AdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already a member? Log in!.
        /// </summary>
        public static string AlreadyMember {
            get {
                return ResourceManager.GetString("AlreadyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Reports.
        /// </summary>
        public static string ClosedReports {
            get {
                return ResourceManager.GetString("ClosedReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string CreatedOn {
            get {
                return ResourceManager.GetString("CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Film.
        /// </summary>
        public static string CreateFilm {
            get {
                return ResourceManager.GetString("CreateFilm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a List.
        /// </summary>
        public static string CreateList {
            get {
                return ResourceManager.GetString("CreateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Show.
        /// </summary>
        public static string CreateShow {
            get {
                return ResourceManager.GetString("CreateShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director(s).
        /// </summary>
        public static string Directors {
            get {
                return ResourceManager.GetString("Directors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disapprove.
        /// </summary>
        public static string Disapprove {
            get {
                return ResourceManager.GetString("Disapprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a Film.
        /// </summary>
        public static string EditFilm {
            get {
                return ResourceManager.GetString("EditFilm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a Show.
        /// </summary>
        public static string EditShow {
            get {
                return ResourceManager.GetString("EditShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Films Are Our Films!.
        /// </summary>
        public static string FeatureFilmTagline {
            get {
                return ResourceManager.GetString("FeatureFilmTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Track of What You Want!.
        /// </summary>
        public static string FeatureListTagline {
            get {
                return ResourceManager.GetString("FeatureListTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Your Thoughts!.
        /// </summary>
        public static string FeatureReviewTagline {
            get {
                return ResourceManager.GetString("FeatureReviewTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film.
        /// </summary>
        public static string Film {
            get {
                return ResourceManager.GetString("Film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilmHaus.
        /// </summary>
        public static string FilmHaus {
            get {
                return ResourceManager.GetString("FilmHaus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film Library.
        /// </summary>
        public static string FilmLibrary {
            get {
                return ResourceManager.GetString("FilmLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Films.
        /// </summary>
        public static string Films {
            get {
                return ResourceManager.GetString("Films", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Films &amp; Shows.
        /// </summary>
        public static string FilmsShows {
            get {
                return ResourceManager.GetString("FilmsShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Films.
        /// </summary>
        public static string FindFilms {
            get {
                return ResourceManager.GetString("FindFilms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Shows.
        /// </summary>
        public static string FindShows {
            get {
                return ResourceManager.GetString("FindShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre(s).
        /// </summary>
        public static string Genres {
            get {
                return ResourceManager.GetString("Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a Question?.
        /// </summary>
        public static string HaveQuestions {
            get {
                return ResourceManager.GetString("HaveQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Login.
        /// </summary>
        public static string LastLogin {
            get {
                return ResourceManager.GetString("LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists.
        /// </summary>
        public static string Lists {
            get {
                return ResourceManager.GetString("Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mohawk College.
        /// </summary>
        public static string MohawkCollege {
            get {
                return ResourceManager.GetString("MohawkCollege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Suggestions.
        /// </summary>
        public static string MovieSuggestions {
            get {
                return ResourceManager.GetString("MovieSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Films.
        /// </summary>
        public static string MyFilms {
            get {
                return ResourceManager.GetString("MyFilms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Lists.
        /// </summary>
        public static string MyLists {
            get {
                return ResourceManager.GetString("MyLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Reports.
        /// </summary>
        public static string MyReports {
            get {
                return ResourceManager.GetString("MyReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Reviews.
        /// </summary>
        public static string MyReviews {
            get {
                return ResourceManager.GetString("MyReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Shows.
        /// </summary>
        public static string MyShows {
            get {
                return ResourceManager.GetString("MyShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New to FilmHaus? Register!.
        /// </summary>
        public static string NewFilmHaus {
            get {
                return ResourceManager.GetString("NewFilmHaus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently have no films in your library.
        /// </summary>
        public static string NoFilms {
            get {
                return ResourceManager.GetString("NoFilms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no films in this list.
        /// </summary>
        public static string NoFilmsList {
            get {
                return ResourceManager.GetString("NoFilmsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no film reviews.
        /// </summary>
        public static string NoFilmsReview {
            get {
                return ResourceManager.GetString("NoFilmsReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently have no shows in your library.
        /// </summary>
        public static string NoShows {
            get {
                return ResourceManager.GetString("NoShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no shows in this list.
        /// </summary>
        public static string NoShowsList {
            get {
                return ResourceManager.GetString("NoShowsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no show reviews.
        /// </summary>
        public static string NoShowsReview {
            get {
                return ResourceManager.GetString("NoShowsReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Seasons.
        /// </summary>
        public static string NumberOfSeasons {
            get {
                return ResourceManager.GetString("NumberOfSeasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsolete.
        /// </summary>
        public static string Obsolete {
            get {
                return ResourceManager.GetString("Obsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsolete a Film.
        /// </summary>
        public static string ObsoleteFilm {
            get {
                return ResourceManager.GetString("ObsoleteFilm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsolete a Show.
        /// </summary>
        public static string ObsoleteShow {
            get {
                return ResourceManager.GetString("ObsoleteShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Sponsor.
        /// </summary>
        public static string OurSponsor {
            get {
                return ResourceManager.GetString("OurSponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Reports.
        /// </summary>
        public static string PastReports {
            get {
                return ResourceManager.GetString("PastReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poster.
        /// </summary>
        public static string Poster {
            get {
                return ResourceManager.GetString("Poster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Mark.
        /// </summary>
        public static string QuestionMark {
            get {
                return ResourceManager.GetString("QuestionMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReleaseYear.
        /// </summary>
        public static string ReleaseYear {
            get {
                return ResourceManager.GetString("ReleaseYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Browser?.
        /// </summary>
        public static string RememberBrowser {
            get {
                return ResourceManager.GetString("RememberBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reported On.
        /// </summary>
        public static string ReportedOn {
            get {
                return ResourceManager.GetString("ReportedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reported Reviews.
        /// </summary>
        public static string ReportedReviews {
            get {
                return ResourceManager.GetString("ReportedReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        public static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve.
        /// </summary>
        public static string Resolve {
            get {
                return ResourceManager.GetString("Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolved On.
        /// </summary>
        public static string ResolvedOn {
            get {
                return ResourceManager.GetString("ResolvedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime.
        /// </summary>
        public static string Runtime {
            get {
                return ResourceManager.GetString("Runtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Films.
        /// </summary>
        public static string SearchFilms {
            get {
                return ResourceManager.GetString("SearchFilms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Lists.
        /// </summary>
        public static string SearchLists {
            get {
                return ResourceManager.GetString("SearchLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Reviews.
        /// </summary>
        public static string SearchReviews {
            get {
                return ResourceManager.GetString("SearchReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Shows.
        /// </summary>
        public static string SearchShows {
            get {
                return ResourceManager.GetString("SearchShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared.
        /// </summary>
        public static string Shared {
            get {
                return ResourceManager.GetString("Shared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Library.
        /// </summary>
        public static string ShowLibrary {
            get {
                return ResourceManager.GetString("ShowLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows.
        /// </summary>
        public static string Shows {
            get {
                return ResourceManager.GetString("Shows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted By.
        /// </summary>
        public static string SubmittedBy {
            get {
                return ResourceManager.GetString("SubmittedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account.
        /// </summary>
        public static string UserAccount {
            get {
                return ResourceManager.GetString("UserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Actions.
        /// </summary>
        public static string UserActions {
            get {
                return ResourceManager.GetString("UserActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Lists.
        /// </summary>
        public static string ViewLists {
            get {
                return ResourceManager.GetString("ViewLists", resourceCulture);
            }
        }
    }
}
